### ISSUE TITLE
Link to screencaster doesn't work on Loki

### ISSUE THREAD

**Issue by jlnr** [artemanufrij/artemanufrij.github.io#1]
Not sure if it's a bug with the website or AppCenter. If I click the link, AppCenter searches for "com.github.artemanufrij.screencaster.desktop" and can't find anything. If I delete the .desktop suffix in the search field, the app appears.

**Comment by artemanufrij** [comment]
wow... thanks for your feedback! will check it out!

**Comment by artemanufrij** [comment]
fixed...
